//
//  TranslatePresenter.swift
//  DragDropTranslate
//
//  Created by Thiago Santiago on 8/26/18.
//  Copyright (c) 2018 Thiago Santiago. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TranslatePresenterDelegate {
    func presentTextTranslated(textTranslated: String)
    func presentError(message: String)
}

class TranslatePresenter: TranslatePresenterDelegate {
    var viewController: DragDropTranslateViewControllerDelegate?
  
    func presentTextTranslated(textTranslated: String) {
        viewController?.showTextTranslated(textTranslated)
    }
    
    func presentError(message: String) {
        viewController?.showErrorMessage(message)
    }
}
