//
//  TranslateInteractor.swift
//  DragDropTranslate
//
//  Created by Thiago Santiago on 8/26/18.
//  Copyright (c) 2018 Thiago Santiago. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TranslateInteractorDelegate {
    func translate(text: String)
}

class TranslateInteractor: TranslateInteractorDelegate {
    let repository = TranslateRepository()
    var presenter: TranslatePresenterDelegate?
    
    func translate(text: String) {
        repository.translateText(text, success: { result in
            self.presenter?.presentTextTranslated(textTranslated: result.data?.translations?.first?.translatedText ?? "")
        }) { error in
            self.presenter?.presentError(message: error)
        }
    }
}
